package com.madeline.entity;
// Generated 2016-10-13 17:27:15 by Hibernate Tools 5.1.0.Beta1

/**
 * Artefact generated by hbm2java
 */
public class Artefact implements java.io.Serializable {

	private Integer artefactid;
	private String title;
	private Boolean isold;
	private Integer roomid;
	private String content;
	private String picture;
	private String audio;
	private String video;
	private Boolean isdeleted;

	public Artefact() {
	}

	public Artefact(String title, Boolean isold, Integer roomid, String content, String picture, String audio,
			String video, Boolean isdeleted) {
		this.title = title;
		this.isold = isold;
		this.roomid = roomid;
		this.content = content;
		this.picture = picture;
		this.audio = audio;
		this.video = video;
		this.isdeleted = isdeleted;
	}

	public Integer getArtefactid() {
		return this.artefactid;
	}

	public void setArtefactid(Integer artefactid) {
		this.artefactid = artefactid;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Boolean getIsold() {
		return this.isold;
	}

	public void setIsold(Boolean isold) {
		this.isold = isold;
	}

	public Integer getRoomid() {
		return this.roomid;
	}

	public void setRoomid(Integer roomid) {
		this.roomid = roomid;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getPicture() {
		return this.picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

	public String getAudio() {
		return this.audio;
	}

	public void setAudio(String audio) {
		this.audio = audio;
	}

	public String getVideo() {
		return this.video;
	}

	public void setVideo(String video) {
		this.video = video;
	}

	public Boolean getIsdeleted() {
		return this.isdeleted;
	}

	public void setIsdeleted(Boolean isdeleted) {
		this.isdeleted = isdeleted;
	}

}
