package com.madeline.entity;
// Generated 2016-10-13 17:27:15 by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

/**
 * Comment generated by hbm2java
 */
public class Comment implements java.io.Serializable {

	private Integer commentid;
	private String title;
	private Boolean isapproved;
	private Integer userid;
	private Integer memoryid;
	private Integer rating;
	private String content;
	private Date publishdate;
	private Boolean isdeleted;

	public Comment() {
	}

	public Comment(String title, Boolean isapproved, Integer userid, Integer memoryid, Integer rating, String content,
			Date publishdate, Boolean isdeleted) {
		this.title = title;
		this.isapproved = isapproved;
		this.userid = userid;
		this.memoryid = memoryid;
		this.rating = rating;
		this.content = content;
		this.publishdate = publishdate;
		this.isdeleted = isdeleted;
	}

	public Integer getCommentid() {
		return this.commentid;
	}

	public void setCommentid(Integer commentid) {
		this.commentid = commentid;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Boolean getIsapproved() {
		return this.isapproved;
	}

	public void setIsapproved(Boolean isapproved) {
		this.isapproved = isapproved;
	}

	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	public Integer getMemoryid() {
		return this.memoryid;
	}

	public void setMemoryid(Integer memoryid) {
		this.memoryid = memoryid;
	}

	public Integer getRating() {
		return this.rating;
	}

	public void setRating(Integer rating) {
		this.rating = rating;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getPublishdate() {
		return this.publishdate;
	}

	public void setPublishdate(Date publishdate) {
		this.publishdate = publishdate;
	}

	public Boolean getIsdeleted() {
		return this.isdeleted;
	}

	public void setIsdeleted(Boolean isdeleted) {
		this.isdeleted = isdeleted;
	}

}
