package com.madeline.entity;
// Generated 2016-9-22 15:31:37 by Hibernate Tools 5.1.0.Beta1

/**
 * Floor generated by hbm2java
 */
public class Floor implements java.io.Serializable {

	private Integer floorid;
	private Integer floornum;
	private String floordescript;

	public Floor() {
	}

	public Floor(Integer floornum, String floordescript) {
		this.floornum = floornum;
		this.floordescript = floordescript;
	}

	public Integer getFloorid() {
		return this.floorid;
	}

	public void setFloorid(Integer floorid) {
		this.floorid = floorid;
	}

	public Integer getFloornum() {
		return this.floornum;
	}

	public void setFloornum(Integer floornum) {
		this.floornum = floornum;
	}

	public String getFloordescript() {
		return this.floordescript;
	}

	public void setFloordescript(String floordescript) {
		this.floordescript = floordescript;
	}

}
