package com.madeline.entity;
// Generated 2016-9-22 15:31:37 by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

/**
 * Memory generated by hbm2java
 */
public class Memory implements java.io.Serializable {

	private Integer memoryid;
	private String title;
	private Boolean isapproved;
	private Integer userid;
	private Integer roomid;
	private String content;
	private String picture;
	private String audio;
	private String video;
	private Float avrrating;
	private Date publishdate;
	private Boolean isdeleted;

	public Memory() {
	}

	public Memory(String title, Boolean isapproved, Integer userid, Integer roomid, String content, String picture,
			String audio, String video, Float avrrating, Date publishdate, Boolean isdeleted) {
		this.title = title;
		this.isapproved = isapproved;
		this.userid = userid;
		this.roomid = roomid;
		this.content = content;
		this.picture = picture;
		this.audio = audio;
		this.video = video;
		this.avrrating = avrrating;
		this.publishdate = publishdate;
		this.isdeleted = isdeleted;
	}

	public Integer getMemoryid() {
		return this.memoryid;
	}

	public void setMemoryid(Integer memoryid) {
		this.memoryid = memoryid;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Boolean getIsapproved() {
		return this.isapproved;
	}

	public void setIsapproved(Boolean isapproved) {
		this.isapproved = isapproved;
	}

	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	public Integer getRoomid() {
		return this.roomid;
	}

	public void setRoomid(Integer roomid) {
		this.roomid = roomid;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getPicture() {
		return this.picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

	public String getAudio() {
		return this.audio;
	}

	public void setAudio(String audio) {
		this.audio = audio;
	}

	public String getVideo() {
		return this.video;
	}

	public void setVideo(String video) {
		this.video = video;
	}

	public Float getAvrrating() {
		return this.avrrating;
	}

	public void setAvrrating(Float avrrating) {
		this.avrrating = avrrating;
	}

	public Date getPublishdate() {
		return this.publishdate;
	}

	public void setPublishdate(Date publishdate) {
		this.publishdate = publishdate;
	}

	public Boolean getIsdeleted() {
		return this.isdeleted;
	}

	public void setIsdeleted(Boolean isdeleted) {
		this.isdeleted = isdeleted;
	}

}
