package com.madeline.entity;
// Generated 2016-9-22 15:31:37 by Hibernate Tools 5.1.0.Beta1

/**
 * RelationUserMemory generated by hbm2java
 */
public class RelationUserMemory implements java.io.Serializable {

	private int memorytid;
	private Integer userid;

	public RelationUserMemory() {
	}

	public RelationUserMemory(int memorytid) {
		this.memorytid = memorytid;
	}

	public RelationUserMemory(int memorytid, Integer userid) {
		this.memorytid = memorytid;
		this.userid = userid;
	}

	public int getMemorytid() {
		return this.memorytid;
	}

	public void setMemorytid(int memorytid) {
		this.memorytid = memorytid;
	}

	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

}
