package com.madeline.entity;
// Generated 2016-9-22 15:31:37 by Hibernate Tools 5.1.0.Beta1

/**
 * RelationRoomArtefact generated by hbm2java
 */
public class RelationRoomArtefact implements java.io.Serializable {

	private int artefactid;
	private Integer roomid;

	public RelationRoomArtefact() {
	}

	public RelationRoomArtefact(int artefactid) {
		this.artefactid = artefactid;
	}

	public RelationRoomArtefact(int artefactid, Integer roomid) {
		this.artefactid = artefactid;
		this.roomid = roomid;
	}

	public int getArtefactid() {
		return this.artefactid;
	}

	public void setArtefactid(int artefactid) {
		this.artefactid = artefactid;
	}

	public Integer getRoomid() {
		return this.roomid;
	}

	public void setRoomid(Integer roomid) {
		this.roomid = roomid;
	}

}
