package com.madeline.entity;
// Generated 2016-10-13 17:27:15 by Hibernate Tools 5.1.0.Beta1

/**
 * RelationRoomMemory generated by hbm2java
 */
public class RelationRoomMemory implements java.io.Serializable {

	private int memorytid;
	private Integer roomid;

	public RelationRoomMemory() {
	}

	public RelationRoomMemory(int memorytid) {
		this.memorytid = memorytid;
	}

	public RelationRoomMemory(int memorytid, Integer roomid) {
		this.memorytid = memorytid;
		this.roomid = roomid;
	}

	public int getMemorytid() {
		return this.memorytid;
	}

	public void setMemorytid(int memorytid) {
		this.memorytid = memorytid;
	}

	public Integer getRoomid() {
		return this.roomid;
	}

	public void setRoomid(Integer roomid) {
		this.roomid = roomid;
	}

}
