package com.madeline.entity;
// Generated 2016-10-13 17:27:15 by Hibernate Tools 5.1.0.Beta1

/**
 * Room generated by hbm2java
 */
public class Room implements java.io.Serializable {

	private Integer roomid;
	private Integer roomnum;
	private Integer floorid;
	private String roomname;
	private String roominfo;

	public Room() {
	}

	public Room(Integer roomnum, Integer floorid, String roomname, String roominfo) {
		this.roomnum = roomnum;
		this.floorid = floorid;
		this.roomname = roomname;
		this.roominfo = roominfo;
	}

	public Integer getRoomid() {
		return this.roomid;
	}

	public void setRoomid(Integer roomid) {
		this.roomid = roomid;
	}

	public Integer getRoomnum() {
		return this.roomnum;
	}

	public void setRoomnum(Integer roomnum) {
		this.roomnum = roomnum;
	}

	public Integer getFloorid() {
		return this.floorid;
	}

	public void setFloorid(Integer floorid) {
		this.floorid = floorid;
	}

	public String getRoomname() {
		return this.roomname;
	}

	public void setRoomname(String roomname) {
		this.roomname = roomname;
	}

	public String getRoominfo() {
		return this.roominfo;
	}

	public void setRoominfo(String roominfo) {
		this.roominfo = roominfo;
	}

}
