package com.madeline.entity;
// Generated 2016-9-22 15:31:37 by Hibernate Tools 5.1.0.Beta1

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer userid;
	private String username;
	private String userpassword;
	private Integer roleid;
	private String rolename;
	private String email;
	private Long phone;
	private String portrait;
	private String description;
	private Boolean issubscribed;

	public User() {
	}

	public User(String username, String userpassword, Integer roleid, String rolename, String email, Long phone,
			String portrait, String description, Boolean issubscribed) {
		this.username = username;
		this.userpassword = userpassword;
		this.roleid = roleid;
		this.rolename = rolename;
		this.email = email;
		this.phone = phone;
		this.portrait = portrait;
		this.description = description;
		this.issubscribed = issubscribed;
	}

	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getUserpassword() {
		return this.userpassword;
	}

	public void setUserpassword(String userpassword) {
		this.userpassword = userpassword;
	}

	public Integer getRoleid() {
		return this.roleid;
	}

	public void setRoleid(Integer roleid) {
		this.roleid = roleid;
	}

	public String getRolename() {
		return this.rolename;
	}

	public void setRolename(String rolename) {
		this.rolename = rolename;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Long getPhone() {
		return this.phone;
	}

	public void setPhone(Long phone) {
		this.phone = phone;
	}

	public String getPortrait() {
		return this.portrait;
	}

	public void setPortrait(String portrait) {
		this.portrait = portrait;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Boolean getIssubscribed() {
		return this.issubscribed;
	}

	public void setIssubscribed(Boolean issubscribed) {
		this.issubscribed = issubscribed;
	}

}
